yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.gpoup_list, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from core.models import CreatedModel
from django.contrib.auth import get_user_model


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


User = get_user_model()

CHAR_Q = 15


class Post(CreatedModel):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
        related_name='posts'
    )
    image = models.ImageField(
        'Изображение',
        help_text='Можно добавить картинку',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-created']

    def __str__(self) -> str:
        return self.text[:CHAR_Q]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )

    def __str__(self) -> str:
        # выводим текст комментария
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='user_author'
            )
        ]

yatube/posts/forms.py
from .models import Post, Comment
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page


TEXT: str = 'Последние обновления на сайте'
FOLLOW_TEXT: str = 'Лента'
POSTS_QUANTITY: int = 10
TIMEOUT: int = 20


@cache_page(TIMEOUT)
def index(request):
    """Показывает главную страницу со всеми постами всех авторов."""
    template_name = 'posts/index.html'
    post_list = Post.objects.select_related('author', 'group').all()
    paginator = Paginator(post_list, POSTS_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'text': TEXT,
        'page_obj': page_obj,
    }
    return render(request, template_name, context)


def gpoup_list(request, slug):
    """Показывает посты выбранной группы."""
    template_name = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    description = group.description
    post_list = group.posts.select_related("author")
    paginator = Paginator(post_list, POSTS_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'text': f'Записи сообщества {group.__str__()}',
        'description': description,
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template_name, context)


def profile(request, username):
    """Показывает посты выбранного автора."""
    template_name = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    user=request.user
    if (
        user.is_authenticated
        and author != user
        and Follow.objects.filter(user=user, author=author).exists()
    ):
        following = True
    else:
        following = False
    post_list = author.posts.select_related('group')
    paginator = Paginator(post_list, POSTS_QUANTITY)
    count = paginator.count
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'count': count,
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template_name, context)


def post_detail(request, post_id):
    """Показывает страницу с детальной информацией о посте."""
    template_name = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    post_list = Post.objects.filter(author_id=post.author).all()
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    count = post_list.count()
    context = {
        'count': count,
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, template_name, context)


@login_required
def post_create(request):
    """Создать новый пост."""
    template_name = 'posts/create_post.html'
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        username = post.author.username
        return redirect('posts:profile', username)
    return render(request, template_name, {'form': form})


def post_edit(request, post_id):
    """Редактировать уже существующий пост."""
    template_name = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if post.author == request.user:
        if form.is_valid():
            post = form.save()
            return redirect('posts:post_detail', post_id)
        return render(request, template_name, {'form': form, 'is_edit': True})
    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request, post_id):
    """Добавить комментарий к посту."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Показывает посты авторов, на которых подписан пользователь."""
    # информация о текущем пользователе доступна в переменной request.user
    template_name = 'posts/follow.html'
    authors = Follow.objects.filter(user=request.user).values('author')
    post_list = Post.objects.filter(author__in=authors).all()
    paginator = Paginator(post_list, POSTS_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'text': FOLLOW_TEXT,
        'following': True,
        'page_obj': page_obj,
    }
    return render(request, template_name, context)


@login_required
def profile_follow(request, username):
    """Подписаться на выбранного автора."""
    author = get_object_or_404(User, username=username)
    user = request.user
    if (
        author != user
        # Проверка существования подписки оставлена, несмотря на прописанный
        # в модели Follow constraint, т.к. тесты Яндекса не были рассчитаны 
        # на constraint и падают.
        # Функциональной нагрузки не несёт.
        and not Follow.objects.filter(author=author, user=user).exists()
    ):
        Follow.objects.create(author=author, user=user)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """Отписаться от выбранного автора."""
    author = get_object_or_404(User, username=username)
    user = request.user
    if (
        author != user
        and Follow.objects.filter(author=author, user=user).exists()
    ):
        follow = Follow.objects.get(author=author, user=user)
        follow.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/includes/comment.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.created }}
      </p>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

yatube/templates/posts/includes/paginator.html
    {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="my-5">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
              Предыдущая
            </a>
          </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active">
                <span class="page-link">{{ i }}</span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              Следующая
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
              Последняя
            </a>
          </li>
        {% endif %}    
      </ul>
    </nav>
{% endif %}

yatube/templates/posts/includes/post.html
<!-- класс py-5 создает отступы сверху и снизу блока -->
<div class="container py-3">
    {% load thumbnail %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        <a href="{% url 'posts:profile' post.author.username %}">
          Все посты пользователя
        </a>
      </li>
      <li>
        Дата публикации: {{ post.created|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" padding=True upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">
      Подробная информация
    </a>
    <br>
    <a href="{% url 'posts:post_detail' post.id %}">
      Комментарии: {{post.comments.count}} 
    </a>
    <br>
    {% if post.group.id != None %} 
    <a href="{% url 'posts:group_list' post.group.slug %}">
      Все записи группы
    </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  </div>
  

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
<div class="container py-3">
  <div class="row">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link 
          {% with request.resolver_match.view_name as view_name %}
          {% if view_name == 'posts:index' %}active{% endif %}
          {% endwith %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link
          {% with request.resolver_match.view_name as view_name %}
          {% if view_name == 'posts:follow_index' %}active{% endif %}
          {% endwith %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
</div>
{% endif %}