yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.gpoup_list, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from core.models import CreatedModel
from django.contrib.auth import get_user_model


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


User = get_user_model()

CHAR_Q = 15


class Post(CreatedModel):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
        related_name='posts'
    )
    image = models.ImageField(
        'Изображение',
        help_text='Можно добавить картинку',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-created']

    def __str__(self) -> str:
        return self.text[:CHAR_Q]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )

    def __str__(self) -> str:
        # выводим текст комментария
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='user_author'
            )
        ]

yatube/posts/forms.py
from .models import Post, Comment
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page


TEXT: str = 'Последние обновления на сайте'
FOLLOW_TEXT: str = 'Лента'
POSTS_QUANTITY: int = 10
TIMEOUT: int = 20


@cache_page(TIMEOUT)
def index(request):
    """Показывает главную страницу со всеми постами всех авторов."""
    template_name = 'posts/index.html'
    post_list = Post.objects.select_related('author', 'group').all()
    paginator = Paginator(post_list, POSTS_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'text': TEXT,
        'page_obj': page_obj,
    }
    return render(request, template_name, context)


def gpoup_list(request, slug):
    """Показывает посты выбранной группы."""
    template_name = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    description = group.description
    post_list = group.posts.select_related("author")
    paginator = Paginator(post_list, POSTS_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'text': f'Записи сообщества {group.__str__()}',
        'description': description,
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template_name, context)


def profile(request, username):
    """Показывает посты выбранного автора."""
    template_name = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    user=request.user
    if (
        user.is_authenticated
        and author != user
        and Follow.objects.filter(user=user, author=author).exists()
    ):
        following = True
    else:
        following = False
    post_list = author.posts.select_related('group')
    paginator = Paginator(post_list, POSTS_QUANTITY)
    count = paginator.count
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'count': count,
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template_name, context)


def post_detail(request, post_id):
    """Показывает страницу с детальной информацией о посте."""
    template_name = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    post_list = Post.objects.filter(author_id=post.author).all()
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    count = post_list.count()
    context = {
        'count': count,
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, template_name, context)


@login_required
def post_create(request):
    """Создать новый пост."""
    template_name = 'posts/create_post.html'
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        username = post.author.username
        return redirect('posts:profile', username)
    return render(request, template_name, {'form': form})


def post_edit(request, post_id):
    """Редактировать уже существующий пост."""
    template_name = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if post.author == request.user:
        if form.is_valid():
            post = form.save()
            return redirect('posts:post_detail', post_id)
        return render(request, template_name, {'form': form, 'is_edit': True})
    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request, post_id):
    """Добавить комментарий к посту."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Показывает посты авторов, на которых подписан пользователь."""
    # информация о текущем пользователе доступна в переменной request.user
    template_name = 'posts/follow.html'
    authors = Follow.objects.filter(user=request.user).values('author')
    post_list = Post.objects.filter(author__in=authors).all()
    paginator = Paginator(post_list, POSTS_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'text': FOLLOW_TEXT,
        'following': True,
        'page_obj': page_obj,
    }
    return render(request, template_name, context)


@login_required
def profile_follow(request, username):
    """Подписаться на выбранного автора."""
    author = get_object_or_404(User, username=username)
    user = request.user
    if (
        author != user
        # Проверка существования подписки оставлена, несмотря на прописанный
        # в модели Follow constraint, т.к. тесты Яндекса не были рассчитаны 
        # на constraint и падают.
        # Функциональной нагрузки не несёт.
        and not Follow.objects.filter(author=author, user=user).exists()
    ):
        Follow.objects.create(author=author, user=user)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """Отписаться от выбранного автора."""
    author = get_object_or_404(User, username=username)
    user = request.user
    if (
        author != user
        and Follow.objects.filter(author=author, user=user).exists()
    ):
        follow = Follow.objects.get(author=author, user=user)
        follow.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
  <head> 
    {% block title %}
      {% if is_edit %}
        Редактировать пост
      {% else %}
        Новый пост
      {% endif %}
    {% endblock %}
  </head>
  <body>
    <main>
      {% block content %}
        <div class="container py-5">
          <div class="row justify-content-center">
            <div class="col-md-8 p-5">
              <div class="card">
                <div class="card-header">     
                  {% if is_edit %}
                    Редактировать пост
                  {% else %}
                    Новый пост
                  {% endif %}             
                </div>
                <div class="card-body">
                  {% load user_filters %}      
                  {% if form.errors %}
                    {% for field in form %}
                      {% for error in field.errors %}            
                        <div class="alert alert-danger">
                          {{ error|escape }}
                        </div>
                      {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endif %}
                  <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                      <div class="form-group row my-3 p-3">
                        <label for="{{ field.id_for_label }}">
                          {{ field.label }}
                            {% if field.field.required %}
                              <span class="required text-danger">*</span>
                            {% endif %}
                        </label>    
                        {{ field|addclass:'form-control' }}
                          {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                             {{ field.help_text|safe }}
                            </small>
                          {% endif %}
                      </div>
                    {% endfor %}
                    <div class="d-flex justify-content-end">
                      <button type="submit" class="btn btn-primary">
                        {% if is_edit %}
                          Сохранить
                        {% else %}
                          Добавить
                        {% endif %}               
                      </button> 
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endblock %}
    </main>
  </body>

yatube/templates/posts/follow.html
{% extends 'base.html' %}
  <head>    
    {% block title %}
    {{ text }}
    {% endblock %}
  </head>
  <body>
    <main> 
      {% block content %}
      {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        {% include 'posts/includes/post.html' %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </main>
      {% endblock %}
  </body>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
  <head>    
    {% block title %}
    {{ text }}
    {% endblock %}
  </head>
  <body>
    <main>
      {% block content %}
      <div class="container pt-5">
        <h1>{% block header %}{{ group.title }}{% endblock %}</h1>
        <p>{{ description }}</p>
      </div>
      {% for post in page_obj %}
        {% include 'posts/includes/post.html' %}
      {% endfor %} 
      {% include 'posts/includes/paginator.html' %}
    </main>
      {% endblock %}
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->
  </body>

yatube/templates/posts/index.html
{% extends 'base.html' %}
  <head>    
    {% block title %}
    {{ text }}
    {% endblock %}
  </head>
  <body>
    <main> 
      {% block content %}
      {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        {% include 'posts/includes/post.html' %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </main>
      {% endblock %}
  </body>

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
  <head>  
    {% block title %}
    Пост {{ post.text|truncatechars:30 }}
    {% endblock %}
  </head>
  <body>       
    <main>
        {% block content %}
        {% load thumbnail %}
        <div class="row py-5 px-5">
            <aside class="col-12 col-md-3">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  Дата публикации: {{ post.created|date:"d E Y" }}
                </li>
                <!-- если у поста есть группа -->
                {% if post.group.id != None %} 
                  <li class="list-group-item"> 
                    Группа: {{ post.group.title }}
                  </li>
                  <li class="list-group-item">
                    <a href="{% url 'posts:group_list' post.group.slug %}">
                      все записи группы
                    </a>
                  </li>
                {% endif %}
                <li class="list-group-item">
                    Автор: {{ post.author.get_full_name }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора:  <span >{{ count }}</span>
                </li>
                <li class="list-group-item">
                  <a href="{% url 'posts:profile' post.author.username %}">
                      все посты пользователя
                  </a>
                </li>
              </ul>
            </aside>
            <article class="col-12 col-md-9">
              {% thumbnail post.image "960x339" padding=True upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
              {% endthumbnail %}
              <p>{{ post.text }}</p>
              {% if post.author == request.user %}
                <a class="btn btn-primary" 
                href="{% url 'posts:post_edit' post.id %}">
                  Редактировать
                </a>
              {% endif %}
              <h5>Комментарии: {{post.comments.count}} </h5>
              {% include 'posts/includes/comment.html' %}
            </article>
        </div> 
    </main>
    {% endblock %}
  </body>
</html>

yatube/templates/posts/profile.html
{% extends 'base.html' %}
  <head> 
    {% block title %}
    Профайл пользователя {{ author.get_full_name }}
    {% endblock %}
  </head>
  <body>
    <main>
        {% block content %}
        <div class="container mb-5">
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <p>Всего постов: {{ count }}</p>
        {% if author != request.user and request.user.is_authenticated %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
        {% endif %}
        </div>
        {% for post in page_obj %}
          {% include 'posts/includes/post.html' %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </main>
        {% endblock %}
  </body>

yatube/templates/posts/update_post.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Редактировать пост</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">              
              <a class="nav-link" href="../about/author.html">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../about/tech.html">
                Технологии
              </a>
            </li>
            <!-- пункты меню видны только авторизованному пользователю -->
            <li class="nav-item">
              <a class="nav-link active" href="../posts/create_post.html">
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/password_change_form.html">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/logged_out.html">Выйти</a>
            </li>
            <li>
              Пользователь: leo
            <li>
            <!-- конец пункты меню видны только авторизованному пользователю -->
            <!-- пункты меню видны только неавторизованному пользователю -->
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/login.html">
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/signup.html">Регистрация</a>
            </li>
            <!-- конец пункты меню видны только неавторизованному пользователю -->        
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="">---------</option>
                      <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>